import streamlit as st
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import io
import datetime
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(
    page_title="GenEpi: Professional Analytics Suite",
    page_icon="🧬",
    layout="wide"
)

# --- 2. PROFESSIONAL STYLING (CSS) ---
st.markdown("""
<style>
    .main { background-color: #f8f9fa; font-family: 'Segoe UI', sans-serif; }
    h1 { color: #2c3e50; font-weight: 700; border-bottom: 2px solid #3498db; padding-bottom: 15px; }
    h2, h3 { color: #34495e; }
    div[data-testid="stMetricValue"] { font-size: 1.5rem; color: #2980b9; }
    div.stButton > button { 
        background-color: #2980b9; color: white; border: none; 
        padding: 10px 20px; border-radius: 5px; font-weight: 600; width: 100%; 
    }
    div.stButton > button:hover { background-color: #1a5276; }
    thead tr th:first-child { display:none }
    tbody th { display:none }
</style>
""", unsafe_allow_html=True)

# --- 3. SESSION STATE INITIALIZATION ---
state_vars = ['meta_data', 'df_case', 'df_ctrl', 'gen_results', 'clin_results', 'meta_img_buf', 'heatmap_img_buf', 'bias_stats']
for var in state_vars:
    if var not in st.session_state:
        st.session_state[var] = None

# --- 4. WORD REPORT GENERATOR ---
def create_word_report(investigator, study_id, date):
    doc = Document()
    
    # Title
    heading = doc.add_heading(f'GenEpi Analysis Report: {study_id}', 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph(f'Investigator: {investigator}')
    doc.add_paragraph(f'Date: {date}')
    doc.add_paragraph('Generated by GenEpi Professional Analytics Suite')
    doc.add_page_break()

    # 1. Genotype Analysis
    if st.session_state['gen_results'] is not None:
        doc.add_heading('1. Genotypic Association Analysis', level=1)
        df = st.session_state['gen_results']
        table = doc.add_table(rows=1, cols=len(df.columns))
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        for i, col in enumerate(df.columns):
            hdr_cells[i].text = str(col)
        for index, row in df.iterrows():
            row_cells = table.add_row().cells
            for i, val in enumerate(row):
                row_cells[i].text = str(val)
        doc.add_paragraph("\n")

    # 2. Clinical Stats
    if st.session_state['clin_results'] is not None:
        doc.add_heading('2. Clinical Variable Analysis (T-Test)', level=1)
        df_clin = st.session_state['clin_results']
        table = doc.add_table(rows=1, cols=len(df_clin.columns))
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        for i, col in enumerate(df_clin.columns):
            hdr_cells[i].text = str(col)
        for index, row in df_clin.iterrows():
            row_cells = table.add_row().cells
            for i, val in enumerate(row):
                row_cells[i].text = str(val)
        doc.add_paragraph("\n")

    # 3. Meta-Analysis
    if st.session_state['meta_img_buf'] is not None:
        doc.add_heading('3. Meta-Analysis & Bias Detection', level=1)
        if st.session_state['bias_stats']:
            stats = st.session_state['bias_stats']
            doc.add_paragraph(f"Egger's Test P-Value: {stats['egger']}")
            doc.add_paragraph(f"Begg's Test P-Value: {stats['begg']}")
        doc.add_heading('Funnel Plot', level=2)
        doc.add_picture(st.session_state['meta_img_buf'], width=Inches(5))
        doc.add_paragraph("\n")

    # 4. Heatmap
    if st.session_state['heatmap_img_buf'] is not None:
        doc.add_heading('4. Clinical Correlation Heatmap', level=1)
        doc.add_picture(st.session_state['heatmap_img_buf'], width=Inches(6))

    bio = io.BytesIO()
    doc.save(bio)
    return bio

# --- 5. SIDEBAR ---
with st.sidebar:
    st.image("https://img.icons8.com/color/96/dna-helix.png", width=60)
    st.title("Project Setup")
    
    st.subheader("1. Upload Data")
    file_case = st.file_uploader("Upload PCOS Cases (.csv)", type=['csv'])
    file_ctrl = st.file_uploader("Upload Controls (.csv)", type=['csv'])
    
    st.subheader("2. Metadata")
    investigator = st.text_input("Investigator", "Dr. Researcher")
    study_id = st.text_input("Study ID", "PCOS_Gen_2025")
    report_date = st.date_input("Date", datetime.date.today())
    
    st.markdown("---")
    if st.button("📄 Generate Report"):
        if any(x is not None for x in [st.session_state['gen_results'], st.session_state['clin_results'], st.session_state['heatmap_img_buf']]):
            docx_file = create_word_report(investigator, study_id, report_date)
            st.download_button("📥 Download Full Report (.docx)", docx_file.getvalue(), f"{study_id}_Report.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        else:
            st.warning("No analysis results found. Run the tests first.")

# --- 6. DATA LOADING ---
def clean_and_normalize(df):
    df.columns = [c.strip().split('(')[0].strip() for c in df.columns]
    for col in df.columns:
        if col not in ['Name', 'Marital Status']:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    return df

if file_case and file_ctrl:
    try:
        df_c = pd.read_csv(file_case, encoding='ISO-8859-1')
        df_n = pd.read_csv(file_ctrl, encoding='ISO-8859-1')
        st.session_state['df_case'] = clean_and_normalize(df_c)
        st.session_state['df_ctrl'] = clean_and_normalize(df_n)
    except Exception as e:
        st.sidebar.error(f"Error loading files: {e}")

# --- 7. STATS FUNCTIONS ---
def highlight_sig(val):
    try: 
        if isinstance(val, str) and "*" in val: return 'background-color: #d4edda; color: #155724; font-weight: bold'
    except: pass
    return ''

def calculate_stat_row(model, event_name, ref_name, a, c, b, d):
    if any(x == 0 for x in [a, b, c, d]): a+=0.5;b+=0.5;c+=0.5;d+=0.5
    try:
        or_val = (a * d) / (b * c)
        log_or = np.log(or_val)
        se = np.sqrt(1/a + 1/b + 1/c + 1/d)
        ci_lo = np.exp(log_or - 1.96 * se)
        ci_up = np.exp(log_or + 1.96 * se)
        _, p, _, _ = stats.chi2_contingency([[a, b], [c, d]], correction=False)
        sig = " *" if p < 0.05 else ""
        return {
            "Model": model, "Comparison": f"{event_name} vs {ref_name}",
            "Case (Event/Ref)": f"{int(a)} / {int(c)}", "Ctrl (Event/Ref)": f"{int(b)} / {int(d)}",
            "OR": round(or_val, 2), "95% CI Lower": round(ci_lo, 2), "95% CI Upper": round(ci_up, 2),
            "P-Value": f"{p:.4f}{sig}", "raw_or": or_val, "raw_lo": ci_lo, "raw_up": ci_up
        }
    except: return None

# --- 8. MAIN INTERFACE ---
st.title(f"🧬 GenEpi Analytics: {study_id}")
st.markdown(f"**Generated for:** {investigator} | **Date:** {report_date}")

tabs = st.tabs(["🧬 Genotype Analysis", "🏥 Clinical Stats", "📚 Meta-Analysis", "🎨 Heatmap Analysis"])

# ================= TAB 1: GENOTYPE =================
with tabs[0]:
    st.subheader("1. Genotypic Association")
    with st.expander("📝 Data Entry", expanded=True):
        c1, c2, c3, c4 = st.columns(4)
        c1.write("Type"); c2.write("Label"); c3.write("Cases"); c4.write("Controls")
        
        c1.write("Homozygote (Ref)")
        n_ref = c2.text_input("Ref", "CC", key="n1")
        case_ref = c3.number_input("Cs Ref", 89, key="c1")
        ctrl_ref = c4.number_input("Ct Ref", 132, key="ct1")

        c1.write("Heterozygote")
        n_het = c2.text_input("Het", "CT", key="n2")
        case_het = c3.number_input("Cs Het", 29, key="c2")
        ctrl_het = c4.number_input("Ct Het", 17, key="ct2")

        c1.write("Homozygote (Risk)")
        n_risk = c2.text_input("Risk", "TT", key="n3")
        case_risk = c3.number_input("Cs Risk", 82, key="c3")
        ctrl_risk = c4.number_input("Ct Risk", 51, key="ct3")

    if st.button("🚀 Run Genetic Analysis"):
        results = []
        ca_al_r, ca_al_f = (2*case_risk)+case_het, (2*case_ref)+case_het
        ct_al_r, ct_al_f = (2*ctrl_risk)+ctrl_het, (2*ctrl_ref)+ctrl_het
        
        results.append(calculate_stat_row("Homozygote", n_risk, n_ref, case_risk, case_ref, ctrl_risk, ctrl_ref))
        results.append(calculate_stat_row("Allelic", n_risk[0], n_ref[0], ca_al_r, ca_al_f, ct_al_r, ct_al_f))
        results.append(calculate_stat_row("Heterozygote", n_het, f"{n_ref}+{n_risk}", case_het, case_ref+case_risk, ctrl_het, ctrl_ref+ctrl_risk))
        results.append(calculate_stat_row("Dominant", f"{n_risk}+{n_het}", n_ref, case_risk+case_het, case_ref, ctrl_risk+ctrl_het, ctrl_ref))
        results.append(calculate_stat_row("Recessive", n_risk, f"{n_het}+{n_ref}", case_risk, case_het+case_ref, ctrl_risk, ctrl_het+ctrl_ref))

        df_res = pd.DataFrame([r for r in results if r])
        st.session_state['gen_results'] = df_res[["Model", "Comparison", "Case (Event/Ref)", "Ctrl (Event/Ref)", "OR", "95% CI Lower", "95% CI Upper", "P-Value"]]
        
        if not df_res.empty:
            meta_row = df_res[df_res['Model'] == 'Allelic'].iloc[0] if not df_res[df_res['Model'] == 'Allelic'].empty else df_res.iloc[0]
            st.session_state['meta_data'] = {'OR': meta_row['raw_or'], 'Lo': meta_row['raw_lo'], 'Hi': meta_row['raw_up'], 'Model': meta_row['Model']}
            st.success("✅ Results Saved!")

        st.dataframe(st.session_state['gen_results'].style.applymap(highlight_sig, subset=["P-Value"]), use_container_width=True)

# ================= TAB 2: CLINICAL STATS =================
with tabs[1]:
    st.subheader("2. Continuous Variable Analysis")
    def_m1, def_s1, def_n1 = 25.5, 4.2, 100.0
    def_m2, def_s2, def_n2 = 22.1, 3.8, 100.0
    
    if st.session_state['df_case'] is not None:
        numeric_cols = st.session_state['df_case'].select_dtypes(include=np.number).columns.tolist()
        selected_var = st.selectbox("Select Variable:", numeric_cols)
        if selected_var:
            col_c = st.session_state['df_case'][selected_var]
            def_m1, def_s1, def_n1 = float(col_c.mean()), float(col_c.std()), float(col_c.count())
            if selected_var in st.session_state['df_ctrl'].columns:
                col_n = st.session_state['df_ctrl'][selected_var]
                def_m2, def_s2, def_n2 = float(col_n.mean()), float(col_n.std()), float(col_n.count())

    c_in, c_out = st.columns([1, 2])
    with c_in:
        m1 = st.number_input("Case Mean", value=def_m1, format="%.2f")
        s1 = st.number_input("Case SD", value=def_s1, format="%.2f")
        n1 = st.number_input("Case N", value=int(def_n1))
        st.markdown("---")
        m2 = st.number_input("Ctrl Mean", value=def_m2, format="%.2f")
        s2 = st.number_input("Ctrl SD", value=def_s2, format="%.2f")
        n2 = st.number_input("Ctrl N", value=int(def_n2))
    
    with c_out:
        if st.button("Calculate T-Test"):
            se_diff = np.sqrt((s1**2/n1) + (s2**2/n2))
            t_stat = (m1 - m2) / se_diff
            df_dof = ((s1**2/n1 + s2**2/n2)**2) / (((s1**2/n1)**2)/(n1-1) + ((s2**2/n2)**2)/(n2-1))
            p_val = 2 * (1 - stats.t.cdf(abs(t_stat), df_dof))
            res_clin = pd.DataFrame({"Metric": ["Mean Diff", "95% CI Lower", "95% CI Upper", "T-Statistic", "P-Value"],
                                     "Value": [m1-m2, (m1-m2)-1.96*se_diff, (m1-m2)+1.96*se_diff, t_stat, p_val]})
            st.session_state['clin_results'] = res_clin
            st.dataframe(res_clin.style.format({"Value": "{:.4f}"}), use_container_width=True)

# ================= TAB 3: META-ANALYSIS =================
with tabs[2]:
    st.subheader("3. Meta-Analysis")
    default_text = "Study A,1.5,1.1,2.0\nStudy B,1.2,0.9,1.6\nStudy C,1.8,1.3,2.5"
    if st.session_state['meta_data']:
        md = st.session_state['meta_data']
        default_text = f"Current Study ({md['Model']}),{md['OR']:.2f},{md['Lo']:.2f},{md['Hi']:.2f}\n" + default_text

    c_dat, c_plot = st.columns(2)
    with c_dat:
        txt = st.text_area("CSV Data", default_text, height=150)
        if st.button("Run Meta-Analysis"):
            try:
                df = pd.read_csv(io.StringIO("Study,OR,LowerCI,UpperCI\n" + txt))
                df['LogOR'] = np.log(df['OR']); df['SE'] = (np.log(df['UpperCI']) - np.log(df['LowerCI'])) / 3.92
                egg_p = sm.OLS(df['LogOR']/df['SE'], sm.add_constant(1/df['SE'])).fit().pvalues['const']
                begg_p = stats.kendalltau(df['LogOR'], df['SE']**2)[1]
                
                # Save & Display
                st.session_state['bias_stats'] = {'egger': f"{egg_p:.4f}", 'begg': f"{begg_p:.4f}"}
                
                b1, b2 = st.columns(2)
                b1.metric("Egger's P", f"{egg_p:.4f}", delta="Bias" if egg_p < 0.05 else "No Bias")
                b2.metric("Begg's P", f"{begg_p:.4f}", delta="Bias" if begg_p < 0.05 else "No Bias")
                
                with c_plot:
                    fig, ax = plt.subplots(figsize=(6, 4))
                    ax.scatter(df['LogOR'], 1/df['SE'], c='#3498db', alpha=0.7, edgecolors='k')
                    ax.set_title("Funnel Plot"); ax.set_xlabel("Log OR"); ax.set_ylabel("Precision")
                    ax.axvline(df['LogOR'].mean(), color='red', linestyle='--')
                    st.pyplot(fig)
                    buf = io.BytesIO(); fig.savefig(buf, format="png"); st.session_state['meta_img_buf'] = buf
            except Exception as e: st.error(f"Error: {e}")

# ================= TAB 4: HEATMAP =================
with tabs[3]:
    st.subheader("🎨 Heatmap Analysis")
    if st.session_state['df_case'] is not None:
        dataset_choice = st.radio("Choose Group:", ["PCOS Cases", "Controls"], horizontal=True)
        target_df = st.session_state['df_case'] if dataset_choice == "PCOS Cases" else st.session_state['df_ctrl']
        valid_cols = [c for c in target_df.columns if target_df[c].dtype in ['float64', 'int64']]
        
        if len(valid_cols) > 1:
            corr = target_df[valid_cols].corr()
            fig, ax = plt.subplots(figsize=(10, 8))
            sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5, ax=ax)
            st.pyplot(fig)
            buf = io.BytesIO(); fig.savefig(buf, format="png"); st.session_state['heatmap_img_buf'] = buf
        else: st.warning("Not enough numeric columns found.")
    else: st.info("Upload files in Sidebar first.")